### Valid Authenticated Access
GET https://cst8919assignment-eahfc6c3hmhfgddv.canadacentral-01.azurewebsites.net/login

### Invalid Access (no token)
GET https://cst8919assignment-eahfc6c3hmhfgddv.canadacentral-01.azurewebsites.net/protected